### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by asubiotto** [borealisnanocubes/borealisnanocubes#2]
- [ ] Integrate twitter streaming into nanocube-binning-csv.
    - [ ] Handle twitter stream as "in-memory csv data" (nanocube friendly)
    - [ ] Get rid of the .dmp file stage (look into how a .dmp file is read into nanocube)
    - [ ] Write tests (also try it out on a static twitter dataset)

**Comment by asubiotto** [comment]
@fdhoff
